import = [ "~/.config/alacritty/themes/tokuonight_storm.toml" ]

[window]
title = "Term-Alacritty"
padding = { x = 10, y = 10 }
blur=true
startup_mode = "Fullscreen"
[font]
normal = { family = "FiraCode Nerd Font Mono", style = "Regular" }
bold = { family = "FiraCode Nerd Font Mono", style = "Bold" }
italic = { family = "FiraCode Nerd Font Mono", style = "Italic" }
bold_italic = { family = "FiraCode Nerd Font Mono", style = "Bold Italic" }
